spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false
server.error.whitelabel.enabled: false

server.error.include-stacktrace: never

student.credits.total.max: 20

logging:
  level:
    root: INFO
    com.melg.schoolapp.repository: DEBUG
    org.springframework.data: DEBUG
    